# Escape Room Phonebook Filter

Run the cells below **one at a time, in order**. Each cell applies one clue from `filter_rules.yaml` to the `current` DataFrame and shows what's left, so you can manually check the elimination at every step.

Re-run the setup cell to reset back to the full list of 1000 names.

In [1]:
import pandas as pd

VOWELS = set("aeiou")


def vowel_count(s: str) -> int:
    return sum(1 for c in s.lower() if c in VOWELS)


def common_letters_ordered(a: str, b: str):
    """Letters common to both strings, in the order they appear in `a`,
    plus whether that same relative order holds in `b`."""
    a, b = a.lower(), b.lower()
    common = sorted(set(a) & set(b), key=a.index)
    positions_in_b = [b.index(c) for c in common]
    in_order = all(positions_in_b[i] <= positions_in_b[i + 1] for i in range(len(positions_in_b) - 1))
    return common, in_order


df = pd.read_csv("../data/phonebook.csv", dtype={"phone": str})
# "special" rows (hotline numbers, no name) aren’t name-elimination candidates.
df = df[df["role"] != "special"].reset_index(drop=True)
current = df.copy()
print(f"Loaded {len(df)} entries.")
current.drop(columns=["role"])  # role hidden while filtering, checked at the end

Loaded 1000 entries.

    first_name last_name     phone
0       Dakila      Abad  218-7812
1     Rochelle      Abad  629-5780
2     Sherilyn      Abad  339-3300
3       Ysabel      Abad  673-8889
4       Josefa    Abella  289-4891
..         ...       ...       ...
995       Roel  Zaragoza  976-3909
996     Rustan  Zaragoza  055-1612
997      Nesty     Zobel  134-1476
998      Glenn   Zulueta  534-4425
999      Irish   Zulueta  922-8954

[1000 rows x 3 columns]

## Rule 1
> First name is not 3 letters long.

In [2]:
before = len(current)
mask = current["first_name"].str.len() != 3
current = current[mask]
print(f"{before} -> {len(current)} remaining.")
current.drop(columns=["role"])

1000 -> 957 remaining.

    first_name last_name     phone
0       Dakila      Abad  218-7812
1     Rochelle      Abad  629-5780
2     Sherilyn      Abad  339-3300
3       Ysabel      Abad  673-8889
4       Josefa    Abella  289-4891
..         ...       ...       ...
995       Roel  Zaragoza  976-3909
996     Rustan  Zaragoza  055-1612
997      Nesty     Zobel  134-1476
998      Glenn   Zulueta  534-4425
999      Irish   Zulueta  922-8954

[957 rows x 3 columns]

## Rule 2
> First name starts with a consonant.

In [3]:
before = len(current)
mask = ~current["first_name"].str[0].str.lower().isin(VOWELS)
current = current[mask]
print(f"{before} -> {len(current)} remaining.")
current.drop(columns=["role"])

957 -> 793 remaining.

    first_name last_name     phone
0       Dakila      Abad  218-7812
1     Rochelle      Abad  629-5780
2     Sherilyn      Abad  339-3300
3       Ysabel      Abad  673-8889
4       Josefa    Abella  289-4891
..         ...       ...       ...
993     Donita  Zaragoza  145-5707
995       Roel  Zaragoza  976-3909
996     Rustan  Zaragoza  055-1612
997      Nesty     Zobel  134-1476
998      Glenn   Zulueta  534-4425

[793 rows x 3 columns]

## Rule 3
> Last name has 5 or more letters.

In [4]:
before = len(current)
mask = current["last_name"].str.len() >= 5
current = current[mask]
print(f"{before} -> {len(current)} remaining.")
current.drop(columns=["role"])

793 -> 750 remaining.

    first_name last_name     phone
4       Josefa    Abella  289-4891
5     Cristina    Abrigo  965-5050
6       Bayani  Agbayani  422-2252
7         Bing  Agbayani  209-4938
8       Junjun  Agbayani  777-2615
..         ...       ...       ...
993     Donita  Zaragoza  145-5707
995       Roel  Zaragoza  976-3909
996     Rustan  Zaragoza  055-1612
997      Nesty     Zobel  134-1476
998      Glenn   Zulueta  534-4425

[750 rows x 3 columns]

## Rule 4
> Last name does not end in a vowel.

In [5]:
before = len(current)
mask = ~current["last_name"].str[-1].str.lower().isin(VOWELS)
current = current[mask]
print(f"{before} -> {len(current)} remaining.")
current.drop(columns=["role"])

750 -> 371 remaining.

    first_name last_name     phone
9     Rovilson   Aguilar  377-3287
10      Divine   Agustin  100-4239
33       Maria   Angeles  118-4279
34     Queenie   Angeles  755-3232
48       Jinky  Asuncion  411-7191
..         ...       ...       ...
967    Michael     Viray  624-7015
968     Realyn     Viray  655-6843
971     Darwin     Yabut  665-5493
973     Joanna     Yabut  075-1344
997      Nesty     Zobel  134-1476

[371 rows x 3 columns]

## Rule 5
> First name contains the letter A.

In [6]:
before = len(current)
mask = current["first_name"].str.lower().str.contains("a")
current = current[mask]
print(f"{before} -> {len(current)} remaining.")
current.drop(columns=["role"])

371 -> 207 remaining.

    first_name last_name     phone
33       Maria   Angeles  118-4279
56     Roxanne   Bagayas  172-9402
58    Claudine    Bagsic  159-2579
59      Ranilo    Bagsic  583-9204
60      Ronald    Bagsic  208-4375
..         ...       ...       ...
963     Rowena  Villegas  156-7135
967    Michael     Viray  624-7015
968     Realyn     Viray  655-6843
971     Darwin     Yabut  665-5493
973     Joanna     Yabut  075-1344

[207 rows x 3 columns]

## Rule 6
> First and last names do not start with the same letter.

In [7]:
before = len(current)
mask = current["first_name"].str[0].str.lower() != current["last_name"].str[0].str.lower()
current = current[mask]
print(f"{before} -> {len(current)} remaining.")
current.drop(columns=["role"])

207 -> 186 remaining.

    first_name last_name     phone
33       Maria   Angeles  118-4279
56     Roxanne   Bagayas  172-9402
58    Claudine    Bagsic  159-2579
59      Ranilo    Bagsic  583-9204
60      Ronald    Bagsic  208-4375
..         ...       ...       ...
963     Rowena  Villegas  156-7135
967    Michael     Viray  624-7015
968     Realyn     Viray  655-6843
971     Darwin     Yabut  665-5493
973     Joanna     Yabut  075-1344

[186 rows x 3 columns]

## Rule 7
> First name has more letters than the last name.

In [8]:
before = len(current)
mask = current["first_name"].str.len() > current["last_name"].str.len()
current = current[mask]
print(f"{before} -> {len(current)} remaining.")
current.drop(columns=["role"])

186 -> 51 remaining.

     first_name  last_name     phone
58     Claudine     Bagsic  159-2579
76      Donabel     Banaag  487-7344
84       Jamila      Batac  849-9080
223   Bonifacio   De Jesus  445-4521
285    Milagros     Fabros  681-9649
301    Liwayway     Fortun  059-3946
314     Rosanna     Galang  144-1586
330      Vivian      Golez  135-5718
340  Flordeliza    Guanzon  288-9909
391     Michael     Jocson  840-3728
393     Rosario      Joson  474-4341
403      Gloria      Kalaw  016-3394
413     Mariano     Lacson  686-1713
435   Bonifacio     Leynes  021-9638
438     Reyland     Leynes  847-7430
446   Christian     Llamas  946-7247
448     Donabel     Lontoc  360-7501
449     Rosanna     Lontoc  952-0436
469  Wilhelmina   Madrigal  018-5940
480    Clarissa    Malapit  680-2711
481   Christian      Malig  982-6652
511   Christian    Marquez  891-5083
581    Lualhati     Olivar  627-8270
615     Genalyn      Palad  388-4422
633     Dranreb     Pastor  936-3974
636     Jonalyn     Pastor  219-3310
643     Jonalyn      Perez  989-8037
661     Cynthia     Quezon  656-2762
664     Rosario     Quezon  226-0710
683      Jamila      Ramos  621-8348
688    Claudine     Rebong  998-5908
706   Bonifacio      Reyes  407-3568
708     Jhanine      Reyes  244-5070
709      Josefa      Reyes  835-0916
712  Flordeliza     Reynes  334-6401
715      Jhoana      Rigor  138-6367
721    Trinidad      Rizal  316-2876
807  Luzviminda     Santos  224-0480
809     Ricardo     Santos  065-6304
820      Glenda      Sicat  876-6643
821      Malaya      Sicat  226-1035
825    Lualhati     Silang  226-9265
835     Rosanna      Solis  054-5882
904    Claudine     Valdez  137-5131
929   Charmaine      Velez  239-4334
960  Wilhelmina  Villaruel  279-6807
962   Charmaine   Villegas  646-0964
967     Michael      Viray  624-7015
968      Realyn      Viray  655-6843
971      Darwin      Yabut  665-5493
973      Joanna      Yabut  075-1344

## Rule 8
> First and last names have the same number of vowels.

In [9]:
before = len(current)
mask = current["first_name"].apply(vowel_count) == current["last_name"].apply(vowel_count)
current = current[mask]
print(f"{before} -> {len(current)} remaining.")
current.drop(columns=["role"])

51 -> 12 remaining.

     first_name  last_name     phone
76      Donabel     Banaag  487-7344
438     Reyland     Leynes  847-7430
480    Clarissa    Malapit  680-2711
511   Christian    Marquez  891-5083
615     Genalyn      Palad  388-4422
633     Dranreb     Pastor  936-3974
636     Jonalyn     Pastor  219-3310
643     Jonalyn      Perez  989-8037
820      Glenda      Sicat  876-6643
960  Wilhelmina  Villaruel  279-6807
968      Realyn      Viray  655-6843
971      Darwin      Yabut  665-5493

## Rule 9
> First and last names share at least one letter.

In [10]:
before = len(current)
mask = current.apply(lambda row: len(set(row["first_name"].lower()) & set(row["last_name"].lower())) > 0, axis=1)
current = current[mask]
print(f"{before} -> {len(current)} remaining.")
current.drop(columns=["role"])

12 -> 11 remaining.

     first_name  last_name     phone
76      Donabel     Banaag  487-7344
438     Reyland     Leynes  847-7430
480    Clarissa    Malapit  680-2711
511   Christian    Marquez  891-5083
615     Genalyn      Palad  388-4422
633     Dranreb     Pastor  936-3974
636     Jonalyn     Pastor  219-3310
820      Glenda      Sicat  876-6643
960  Wilhelmina  Villaruel  279-6807
968      Realyn      Viray  655-6843
971      Darwin      Yabut  665-5493

## Rule 10
> The first and last names have exactly two letters in common, and those letters appear in the same order in both names.

In [11]:
before = len(current)
mask = current.apply(lambda row: (lambda c, ordered: len(c) == 2 and ordered)(*common_letters_ordered(row["first_name"], row["last_name"])), axis=1)
current = current[mask]
print(f"{before} -> {len(current)} remaining.")
current.drop(columns=["role"])

11 -> 1 remaining.

    first_name last_name     phone
615    Genalyn     Palad  388-4422

## Final Answer

In [12]:
assert len(current) == 1, f"expected exactly 1 survivor, got {len(current)}"
assert current["role"].iloc[0] == "target", f"survivor's role is {current['role'].iloc[0]!r}, not 'target'"
print("Matches the target row. Puzzle checks out.")
current.drop(columns=["role"])

Matches the target row. Puzzle checks out.

    first_name last_name     phone
615    Genalyn     Palad  388-4422